---
name: redis-deployment

releases:
- name: redis
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: redis
  azs: [z1]
  instances: 1
  persistent_disk_type: 1GB
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: redis
    release: redis
    properties: {}
  update:
    serial: true
    max_in_flight: 1

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000